// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZCXsGF_rJcvZ3qDUG_s4K2LkhmZdD6mQ',
    appId: '1:268126972165:web:32e72fe551652f627e2f6c',
    messagingSenderId: '268126972165',
    projectId: 'wheeltrip-bb5f2',
    authDomain: 'wheeltrip-bb5f2.firebaseapp.com',
    databaseURL: 'https://wheeltrip-bb5f2-default-rtdb.firebaseio.com',
    storageBucket: 'wheeltrip-bb5f2.firebasestorage.app',
    measurementId: 'G-WRYENT8ZDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS-Si8sUSBpCc-vodSgbTGrTvcyaNeD8I',
    appId: '1:268126972165:android:da086b1fd28f9d367e2f6c',
    messagingSenderId: '268126972165',
    projectId: 'wheeltrip-bb5f2',
    databaseURL: 'https://wheeltrip-bb5f2-default-rtdb.firebaseio.com',
    storageBucket: 'wheeltrip-bb5f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7QN3eKKtUGm8kKfCWJq6kjcX5m3ptVhQ',
    appId: '1:268126972165:ios:dcf07216cb0f51dc7e2f6c',
    messagingSenderId: '268126972165',
    projectId: 'wheeltrip-bb5f2',
    databaseURL: 'https://wheeltrip-bb5f2-default-rtdb.firebaseio.com',
    storageBucket: 'wheeltrip-bb5f2.firebasestorage.app',
    iosBundleId: 'com.example.wheeltrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7QN3eKKtUGm8kKfCWJq6kjcX5m3ptVhQ',
    appId: '1:268126972165:ios:dcf07216cb0f51dc7e2f6c',
    messagingSenderId: '268126972165',
    projectId: 'wheeltrip-bb5f2',
    databaseURL: 'https://wheeltrip-bb5f2-default-rtdb.firebaseio.com',
    storageBucket: 'wheeltrip-bb5f2.firebasestorage.app',
    iosBundleId: 'com.example.wheeltrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZCXsGF_rJcvZ3qDUG_s4K2LkhmZdD6mQ',
    appId: '1:268126972165:web:896463a18f7079e67e2f6c',
    messagingSenderId: '268126972165',
    projectId: 'wheeltrip-bb5f2',
    authDomain: 'wheeltrip-bb5f2.firebaseapp.com',
    databaseURL: 'https://wheeltrip-bb5f2-default-rtdb.firebaseio.com',
    storageBucket: 'wheeltrip-bb5f2.firebasestorage.app',
    measurementId: 'G-9RVLECXFHR',
  );

}